name: Throne build matrix
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag and version"
        required: true
      publish:
        description: "r for normal release, p for prerelease, leave empty to not publish anything"
        required: false

jobs:
  build-go:
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - cross_os: windows
            cross_arch: amd64
            go_version: "1.25.3"
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checking out sources
        uses: actions/checkout@v4.2.2

      - name: Cache Common Download
        id: cache-common
        uses: actions/cache@v4.2.3
        with:
          path: artifacts.tgz
          key: CommonCache-${{ matrix.cross_os }}-${{ matrix.cross_arch }}-${{ hashFiles('script/build_go.sh', 'core/*') }}-${{ matrix.go_version }}

      - name: Install Golang
        if: steps.cache-common.outputs.cache-hit != 'true'
        uses: actions/setup-go@v5.5.0
        with:
          go-version: ${{ matrix.go_version }}
          cache-dependency-path: |
            core/server/go.sum

      - name: Install Protoc
        run: |
          curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v31.1/protoc-31.1-linux-x86_64.zip"
          unzip "protoc-31.1-linux-x86_64.zip" -d protoc_install
          cp ./protoc_install/bin/protoc /usr/local/bin
          protoc --version

      - name: Installing protoc-gen-go
        run: |
          go install github.com/golang/protobuf/protoc-gen-go@latest
          go install github.com/chai2010/protorpc/protoc-gen-protorpc@latest

      - name: Build golang parts
        if: steps.cache-common.outputs.cache-hit != 'true'
        shell: bash
        run: |
          GOOS=${{ matrix.cross_os }} GOARCH=${{ matrix.cross_arch }} ./script/build_go.sh

      - name: Tar files
        if: steps.cache-common.outputs.cache-hit != 'true'
        run: tar czvf artifacts.tgz ./deployment

      - name: Uploading Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Throne-${{ github.sha }}-Common-${{ matrix.cross_os }}-${{ matrix.cross_arch }}
          path: artifacts.tgz

  build-cpp:
    permissions:
      contents: read
    needs:
      - build-go
    strategy:
      matrix:
        include:
          - platform: windows-latest
            qt_version: "6.10.1"
            target: x86_64
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      INPUT_VERSION: ${{ github.event.inputs.tag }}
    steps:
      - name: Checking out sources
        uses: actions/checkout@v4.2.2
        with:
          submodules: "recursive"

      - name: Install mingw
        if: matrix.platform == 'windows-latest'
        uses: bwoodsend/setup-winlibs-action@v1.15
        with:
          architecture: ${{ matrix.target }}

      - name: Download Artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          path: download-artifact

      # ========================================================================================================= Qt Install
      - name: Qt static Cache
        id: cache-static-Qt
        if: matrix.platform == 'windows-latest' && matrix.qt_version != '6.2.12'
        uses: actions/cache@v4.2.3
        with:
          path: qt6/build
          key: QtStaticCache-${{ matrix.platform }}-${{ matrix.target }}-Qt${{ matrix.qt_version }}

      - name: Install Qt Windows
        shell: powershell
        if: matrix.platform == 'windows-latest' && steps.cache-static-Qt.outputs.cache-hit != 'true' && matrix.qt_version != '6.2.12'
        run: ./script/build_qt_static_windows.bat ${{ matrix.qt_version }}

      # ========================================================================================================= Generate MakeFile and Build
      - name: Windows - Generate MakeFile and Build
        shell: bash
        if: matrix.platform == 'windows-latest' && matrix.qt_version != '6.2.12'
        run: |
          export CMAKE_PREFIX_PATH=$PWD/qt6/build/lib/cmake
          mkdir build
          cd build
          curl -fLso srslist.h "https://raw.githubusercontent.com/throneproj/routeprofiles/rule-set/srslist.h"
          cmake -GNinja -DCMAKE_CXX_FLAGS="-static" -DCMAKE_BUILD_TYPE=Debug ..
          ninja
          cd ..
          ./script/deploy_windows.sh

      - name: Build Installer with NSIS
        shell: cmd
        if: matrix.platform == 'windows-latest' && matrix.qt_version != '6.2.12'
        run: |
          choco install nsis
          cp .\script\windows_installer.nsi .
          "C:\Program Files (x86)\NSIS\makensis.exe" windows_installer.nsi
          cp ThroneSetup.exe deployment/

      # ========================================================================================================= Deployments
      - name: Tar files
        shell: bash
        run: tar czvf artifacts.tgz ./deployment

      - name: Uploading Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Throne-${{ github.sha }}-${{ matrix.platform }}-${{ matrix.target }}-Qt${{ matrix.qt_version }}
          path: artifacts.tgz

  publish:
    name: Pack & Publish Release
    runs-on: ubuntu-latest
    needs:
      - build-cpp
    permissions:
      contents: write
      actions: read
    env:
      INPUT_VERSION: ${{ github.event.inputs.tag }}
    steps:
      - name: Checking out sources
        uses: actions/checkout@v4.2.2

      - name: Download Artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          path: download-artifact

      - name: Pack (Windows x64 installer only)
        run: |
          curl -Lo - https://github.com/tcnksm/ghr/releases/download/v0.17.0/ghr_v0.17.0_linux_amd64.tar.gz | tar xzv
          mv ghr*linux_amd64/ghr .
          source script/env_deploy.sh
          find . -name artifacts.tgz | xargs -n1 tar xvzf
          cd deployment
          rm -rf *.pdb win*/*.pdb || true

          # Keep installer only
          mv ThroneSetup.exe $version_standalone-windows64-installer.exe
          find . -mindepth 1 -maxdepth 1 ! -name "$version_standalone-windows64-installer.exe" -exec rm -rf {} +

      - name: Uploading Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Deployment-${{ github.sha }}
          path: deployment

      - name: PreRelease
        if: github.event.inputs.publish == 'p'
        run: |
          ./ghr -prerelease -delete -t "${{ github.token }}" -n "${{ github.event.inputs.tag }}" "${{ github.event.inputs.tag }}" deployment

      - name: Release
        if: github.event.inputs.publish == 'r'
        run: |
          ./ghr -delete -t "${{ github.token }}" -n "${{ github.event.inputs.tag }}" "${{ github.event.inputs.tag }}" deployment
